//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Web.ClinicalInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblDiagnoseTypeFlag;
	protected global::System.Web.UI.WebControls.Label lblDiagnoseDateTime;
	protected global::System.Web.UI.WebControls.Label lblRegisterID;
	protected global::System.Web.UI.WebControls.Label lblInPatientID;
	protected global::System.Web.UI.WebControls.Label lblICDCode;
	protected global::System.Web.UI.WebControls.Label lblDiseaseName;
	protected global::System.Web.UI.WebControls.Label lblDescription;


       
    }
}
