//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Web.FP_UserFields {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lbluserFieldId;
	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblobj_id;
	protected global::System.Web.UI.WebControls.Label lbldisplay_name;
	protected global::System.Web.UI.WebControls.Label lblname;
	protected global::System.Web.UI.WebControls.Label lbltype;
	protected global::System.Web.UI.WebControls.Label lblvalues;
	protected global::System.Web.UI.WebControls.Label lblshow;
	protected global::System.Web.UI.WebControls.Label lblcreated_at;
	protected global::System.Web.UI.WebControls.Label lblupdated_at;
	protected global::System.Web.UI.WebControls.Label lblinuse;


       
    }
}
