//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Web.BasedInfo {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtPatientName;
		protected global::System.Web.UI.WebControls.TextBox txtIPSeqNoText;
		protected global::System.Web.UI.WebControls.TextBox txtPatientCardNo;
		protected global::System.Web.UI.WebControls.TextBox txtSexFlag;
		protected global::System.Web.UI.WebControls.TextBox txtBirthday;
		protected global::System.Web.UI.WebControls.TextBox txtBloodTypeFlag;
		protected global::System.Web.UI.WebControls.TextBox txtPhone;
		protected global::System.Web.UI.WebControls.TextBox txtContactPhone;
		protected global::System.Web.UI.WebControls.TextBox txtContactPerson;
		protected global::System.Web.UI.WebControls.TextBox txtNativePlace;
		protected global::System.Web.UI.WebControls.TextBox txtRegisterSeqNO;
		protected global::System.Web.UI.WebControls.TextBox txtPatientID;
		protected global::System.Web.UI.WebControls.TextBox txtRegisterID;
		protected global::System.Web.UI.WebControls.TextBox txtInPatientID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
