//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Web.BasedInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblPatientName;
	protected global::System.Web.UI.WebControls.Label lblIPSeqNoText;
	protected global::System.Web.UI.WebControls.Label lblPatientCardNo;
	protected global::System.Web.UI.WebControls.Label lblSexFlag;
	protected global::System.Web.UI.WebControls.Label lblBirthday;
	protected global::System.Web.UI.WebControls.Label lblBloodTypeFlag;
	protected global::System.Web.UI.WebControls.Label lblPhone;
	protected global::System.Web.UI.WebControls.Label lblContactPhone;
	protected global::System.Web.UI.WebControls.Label lblContactPerson;
	protected global::System.Web.UI.WebControls.Label lblNativePlace;
	protected global::System.Web.UI.WebControls.Label lblRegisterSeqNO;
	protected global::System.Web.UI.WebControls.Label lblPatientID;
	protected global::System.Web.UI.WebControls.Label lblRegisterID;
	protected global::System.Web.UI.WebControls.Label lblInPatientID;


       
    }
}
