//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Web.FP_Users {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lbluserID;
		protected global::System.Web.UI.WebControls.TextBox txtid;
		protected global::System.Web.UI.WebControls.TextBox txtobj_id;
		protected global::System.Web.UI.WebControls.TextBox txtusername;
		protected global::System.Web.UI.WebControls.TextBox txtfullname;
		protected global::System.Web.UI.WebControls.TextBox txtemail;
		protected global::System.Web.UI.WebControls.TextBox txtcreated_at;
		protected global::System.Web.UI.WebControls.TextBox txtdisabled;
		protected global::System.Web.UI.WebControls.TextBox txtactive;
		protected global::System.Web.UI.WebControls.TextBox txtrole;
		protected global::System.Web.UI.WebControls.TextBox txtsamples;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
