//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Web.FP_Users {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lbluserID;
	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblobj_id;
	protected global::System.Web.UI.WebControls.Label lblusername;
	protected global::System.Web.UI.WebControls.Label lblfullname;
	protected global::System.Web.UI.WebControls.Label lblemail;
	protected global::System.Web.UI.WebControls.Label lblcreated_at;
	protected global::System.Web.UI.WebControls.Label lbldisabled;
	protected global::System.Web.UI.WebControls.Label lblactive;
	protected global::System.Web.UI.WebControls.Label lblrole;
	protected global::System.Web.UI.WebControls.Label lblsamples;


       
    }
}
